---
- hosts: windows10
  gather_facts: no
  
  # environment:
  #   HTTP_PROXY: '127.0.0.1:1080'
  #   HTTPS_PROXY: '127.0.0.1:1080'

  tasks:
  - name: ping
    win_ping:
    
  - name: Install choco
    include_tasks: ../../packages/choco.yml
    tags: core

  - name: Install some more chocolatey software
    win_chocolatey:
      name: 
        - vlc
        - audacity
        - calibre

  # Install scoop first from https://scoop.sh/
  - name: Install scoop
    include_tasks: ../../packages/scoop.yml
    tags: core

  - name: Enable TelnetClient
    win_optional_feature:
      name: TelnetClient
      state: present
    
  - name: Install Microsoft Subsystem for Linux
    win_optional_feature:
      name: Microsoft-Windows-Subsystem-Linux
      state: present
    register: wsl_status
  - debug: var=wsl_status

  - name: reboot_required
    block:
      - name: "win_reboot if reboot_required"
        debug: var=wsl_status

      # - win_reboot:
        # when: wsl_status.reboot_required