---
- hosts: windows10
  gather_facts: no
  
  # environment:
  #   HTTP_PROXY: '127.0.0.1:1080'
  #   HTTPS_PROXY: '127.0.0.1:1080'

  tasks:
  - name: ping
    win_ping:

  # https://www.thewindowsclub.com/enable-remote-desktop-using-command-line
  # reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
  # netsh advfirewall firewall set rule group="remote desktop" new enable=yes

  - name: Enable Remote Desktop
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      data: 0
      type: dword

  - name: Enable Remote Desktop
    win_shell: netsh advfirewall firewall set rule group="remote desktop" new enable=yes
    
  - name: Ping choco
    include_tasks: ../../packages/choco.yml
    tags: ping
    
  - name: Install choco
    include_tasks: ../../packages/choco.yml
    tags: core

  - name: Install some more chocolatey software
    win_chocolatey:
      name: 
        - vlc
        - audacity
        - calibre

  - name: Install vagrant matches current Ubuntu version
    win_chocolatey:
      name: 
        - vagrant
      version: 2.2.6

  # ansible-galaxy collection install community.windows
  - name: Install scoop
    include_tasks: ../../packages/scoop.yml
    tags: core

  - name: Enable TelnetClient
    win_optional_feature:
      name: TelnetClient
      state: present

  - name: Firewall rule to allow SSH on TCP port 22
    win_firewall_rule:
      name: SSH
      localport: 22
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
    
  - name: Install Microsoft Subsystem for Linux
    win_optional_feature:
      name: Microsoft-Windows-Subsystem-Linux
      state: present
    register: wsl_status
  - debug: var=wsl_status
    
  - name: Install VirtualMachinePlatform
    win_optional_feature:
      name: VirtualMachinePlatform
      state: present
    register: vmp_status
  - debug: var=vmp_status

  - name: reboot_required
    block:
      - name: "win_reboot if reboot_required"
        debug: var=wsl_status

      - win_reboot:
        when: wsl_status.reboot_required or vmp_status.reboot_required